version: '3.3'

services:
  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - ncs3-network


  ncs3:
    image: ncs3
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - ncs3-network

networks:
  ncs3-network: